### ISSUE TITLE
Does this work when you have a load balanced server?

### ISSUE THREAD

**Issue by jchannon** [i4004/Owin.Security.AesDataProtectorProvider#1]
If you have a load balanced server you would need a shared key. Is it possible with this library?

**UPDATE** : I believe it would after seeing this line?? https://github.com/i4004/Owin.Security.AesDataProtectorProvider/blob/master/Owin.Security.AesDataProtectorProvider/AppBuilderExtensions.cs#L16

**Comment by i4004** [comment]
Yes, you can pass your own key and it will be used on all machines (instances).
