### ISSUE TITLE
Memory leak when reading bytes.

### ISSUE THREAD

**Issue by Thorium** [i4004/Owin.Security.AesDataProtectorProvider#6]
Any ideas on this?

I'm using Microsoft Owin static files server, Kentor cookie saver and AesDataProtectorProvider:
```
Owin.Security.AesDataProtectorProvider (1.1.1)
Kentor.OwinCookieSaver (1.1.1)
Microsoft.Owin.StaticFiles (3.1)
```

My Owin registration (in fsharp, but csharp would be very similar):

```fsharp
    member __.Configuration(ap:Owin.IAppBuilder) =
        ap.UseAesDataProtectorProvider("my-key") |> ignore
        ap.UseKentorOwinCookieSaver() |> ignore
        ap.UseFileServer(fileServerOptions) |> ignore
```

For some reasons sometimes the server hangs (with Chrome) and starts to leak a huge amount of memory. When debugged, it seems to raise the following exception, the callstack won't have my code at all:

{"Non-negative number required.\r\nParameter name: count"}	System.ArgumentOutOfRangeException
	mscorlib.dll!System.IO.BinaryReader.ReadBytes(int count)	Unknown
 	Owin.Security.AesDataProtectorProvider.dll!Owin.Security.AesDataProtectorProvider.AesDataProtector.Unprotect(byte[] protectedData)	Unknown
 	Microsoft.Owin.Security.dll!Microsoft.Owin.Security.DataHandler.SecureDataFormat<Microsoft.Owin.Security.AuthenticationTicket>.Unprotect(string protectedText)	Unknown
 	Microsoft.Owin.Security.Cookies.dll
--cut--
 	mscorlib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP)	Unknown

**Comment by Thorium** [comment]
Changing UseAesDataProtectorProvider key seems to help, at least for now, I don't know why.

**Comment by i4004** [comment]
Sorry, don't know why.

**Comment by i4004** [comment]
Can you try to reproduce the problem?

**Comment by Thorium** [comment]
This is something to do with OWIN server browser caching. If I run my Chrome in incognito-window, everything is working fine.

**Comment by Thorium** [comment]
I managed to create a little console application to emulate the situation without any other related components.

This needs references only to Owin.Security.AesDataProtectorProvider.dll and Microsoft.Owin.Security.dll

```csharp
using Owin.Security.AesDataProtectorProvider.CrypticProviders;
using System;
using System.Collections.Generic;
using System.Linq;

class Program
{
    static void Main(string[] args)
    {
        var purposes = new[] {
            "Microsoft.Owin.Security.Cookies.CookieAuthenticationMiddleware",
            "ApplicationCookie",
            "v1"
        };

        var authCookie = "eLnczc+4i2AwIDknRD90lwEg/qVRgh9yi2oGd9QF8mO/UpgYJyQPQN885qx3tshalkwF5UGRqyHgO6e2t0UHxLBqdO/QWzSNFrbxMDV7mlRfCKF9tfv+Oi+iwNwWAQe/AAWzpZMU/jt6aKFEvDlu5lTx9NMQPANZsTIaRAHD8guje8ltGFJeSDQ8FgyMnzZjBMw8FyiiKYbX5ToFSVoPgsf/6bxlev2QiuYnSkqVsIwMwiCFdUC2fFuj2MouFmipi3dNQDxt+Ihjxff1aBNfI0H2AzDRFtpEyxDSdq/kcMXipkZWSHsfJQaPL9HbJivksQnvg2IUiZWOVn8FOABx0IbjJFzWCQWF1KrdYfCjsLPv/N4LZVJqvyolxHiBBkmM6OrM4WI1+yPndLhoVgUPsg==";
        var protectedData = System.Convert.FromBase64String(authCookie);

        var provider = 
            new Owin.Security.AesDataProtectorProvider.AesDataProtectorProvider(
                new Sha512CspFactory(),
                new Sha256CspFactory(),
                new AesCspFactory(),
                "abcdefg-keyabcx");


        var p = provider.Create(purposes).Unprotect(protectedData);

        Console.WriteLine(p.ToString());
        Console.ReadLine();
    }
}
```

This will fail as 'Padding is invalid and cannot be removed.'
but also this little console app will take momentarily over 1 GB of memory.
Which makes it easy-to-do DoS-attack to OWIN webserver with invalid cookies.

**Comment by Thorium** [comment]
My problem here is somehow related to binary cookies and their base64encoding.

However, the underlying issue is also a security issue. **Just give a cookie with large enough length parameter and the server will crash (bytes after 32 hash in the cookie). This should apply to all users of Owin.Security.AesDataProtectorProvider.** I think that it could be fixed by including also a hash of data.Length and when decrypting, check that first: if the length-hashes doesn't match, then skip the whole `brDecrypt.ReadBytes(len)`. What do you think?

**Comment by Thorium** [comment]
Confirmed, the new PR does fix the problem. 
Ping @i4004

**Comment by i4004** [comment]
So, the correct behavior in that case should be throwing new SecurityException("Data length integrity check failed") exception?

**Comment by Thorium** [comment]
Yes. If the cookie is invalid (or user has lied the data length), it will throw exception. It seems that OWIN can handle that correctly. In my case, it aborts the session cookie, so user has to login again.

**Comment by i4004** [comment]
Only one problem is here, when SecurityException("Data length integrity check failed") is thrown then CryptoStream.Dispose (called because of using block) ignores that and throws CryptographicException with padding error text hiding actual exception.

**Comment by Thorium** [comment]
Should we do something about that?
And will you be releasing a new version to Nuget soon? :-)

**Comment by i4004** [comment]
I will release new version right after we do something about that :)
How you think it is ok to keep that CryptographicException exception?

Or maybe i shoud do like this:
```csharp
try
{
	csDecrypt.Dispose();
}
catch (CryptographicException)
{
}
```

**Comment by Thorium** [comment]
If you talk about the test `Unprotect_CookieWhichCausesLengthIntegrityCheckError_ExceptionThrown`, the authCookie data is invalid for that key, I changed the key from the one I used in production. So it should fail for SecurityException and not CryptographicException but compared to the current production version this is still a huge improvement. :-)

**Comment by i4004** [comment]
The problem here what it is failing correctly but exception is hide by dispose exceptions.
So i end up with this:
```csharp
finally
{
	try
	{
		brDecrypt.Dispose();
		csDecrypt.Dispose();
	}
	catch (CryptographicException)
	{
	}
}
```

**Comment by Thorium** [comment]
Yes I see it's not optimal but can't figure any better now. 

Great, thanks!
